resolver: lts-11.7

packages:
- .
- location:
    git: https://github.com/f-o-a-m/hs-web3
    commit: a911779efa4b1bd9963b3a65a57711660661392b
  extra-dep: true
- location:
    git: https://github.com/tomjaguarpaw/haskell-opaleye
    commit: 77aa17e0e83da0a16fd8daf770833d6e00ca88e6
- location:
    git: https://github.com/blinky3713/composite
    commit: ae46b52f0ea6f963a89aa1b2e3aa051a58adebfd
  subdirs:
    - composite-aeson
    - composite-base
    - composite-opaleye
    - composite-swagger
  extra-dep: true

extra-deps:
 - relapse-1.0.0.0
 - secp256k1-0.5.2


allow-newer: true



