resolver: lts-11.7

packages:
- .
- location:
    git: https://github.com/f-o-a-m/hs-web3
    commit: b45fcbf4f5492c823589194639defe204ec3d5dc
  extra-dep: true
- location:
    git: https://github.com/tomjaguarpaw/haskell-opaleye
    commit: 1f99306b7eb8cc3c3274f615444200738bdfa3b4
  extra-dep: true
- location:
    git: https://github.com/blinky3713/composite
    commit: ae46b52f0ea6f963a89aa1b2e3aa051a58adebfd
  extra-dep: true
  subdirs:
    - composite-aeson
    - composite-base
    - composite-opaleye
    - composite-swagger
  extra-dep: true

extra-deps:
 - relapse-1.0.0.0
 - secp256k1-0.5.2
 - haxl-2.0.1.0


allow-newer: true



