resolver: lts-9.13

packages:
- .
- location:
    git: https://github.com/f-o-a-m/hs-web3
    commit: 814fd555f128efac8855843cd52f4848deae739c
  extra-dep: true
- location:
    git: https://github.com/ConferHealth/composite
    commit: 93c1e14c5f1d36a728631e5ffe0807abafeb80df
  subdirs:
    - composite-aeson
    - composite-base
    - composite-opaleye
    - composite-swagger
  extra-dep: true

extra-deps:
 - sized-0.3.0.0
 - equational-reasoning-0.5.1.0
 - ghc-typelits-presburger-0.2.0.0
 - type-natural-0.8.0.0
