resolver: lts-11.2

packages:
- .
- location:
    git: https://github.com/f-o-a-m/hs-web3
    commit: 814fd555f128efac8855843cd52f4848deae739c
  extra-dep: true
- location:
    git: https://github.com/blinky3713/composite
    commit: ae46b52f0ea6f963a89aa1b2e3aa051a58adebfd
  subdirs:
    - composite-aeson
    - composite-base
    - composite-opaleye
    - composite-swagger
  extra-dep: true
- location:
    git: https://github.com/blinky3713/haskell-opaleye
    commit: e1c79ab13e232f892b0211c4f055464712f0b0f5
  extra-dep: true

extra-deps:
 - sized-0.3.0.0
 - equational-reasoning-0.5.1.0
 - ghc-typelits-presburger-0.2.0.0
 - type-natural-0.8.0.0

allow-newer: true



